### ISSUE TITLE
bilibili任务不执行，求解

### ISSUE THREAD

**Issue by kissfast** [TNanko/leam#41]
使用的是docker部署的，进去之后，手动运行命令：
root@tnanko_scripts:/Scripts/scripts $ python bilibili.py 
获取最新配置文件版本成功！
当前配置文件为最新版本
检测到最新的脚本版本号为v1.1.1，当前脚本版本号：v1.0.0
未执行该任务，如需执行请在配置文件的对应的任务中，将参数 enable 设置为 true

检查了config.yaml，确实修改为true：
bilibili:
    # 使用前请阅读 https://github.com/TNanko/leam/blob/leam/docs/bilibili.md
    enable: true # true 启用脚本； false 不启用脚本（默认不启用脚本）
    version: v1.1.1
    skip_check_script_version: false # 默认不跳过版本检测
    notify: true # true 启用消息推送； false 不启用消息推送（默认发消息推送）
    notify_mode:  # 如果全都配置了，可以根据自身需求进行消息推送方式的选择，不需要的可以注释掉或者删除。推荐 bark
    # - bark
    # - telegram_bot
    # - dingding_bot
      - server_chan
    scripts_filename: 'bilibili.py'
然后手动把github里面的biblibili.py的内容复制替换了docker里面的文件
再次运行，还是报同样的错误
求解

**Comment by kissfast** [comment]
然后，我直接wget了这个bilibili.py，再次运行，这次显示如下：
获取最新配置文件版本成功！
当前配置文件为最新版本
检测到最新的脚本版本号为v1.1.1，当前脚本版本号：v1.0.0
Traceback (most recent call last):
  File "/Scripts/scripts/bilibili.py", line 153, in <module>
    main()
  File "/Scripts/scripts/bilibili.py", line 149, in main
    bilibili()
  File "/Scripts/scripts/bilibili.py", line 111, in bilibili
    content += f"【bilibili】签到失败！说明：{sign_result['message']}"
TypeError: 'NoneType' object is not subscriptable

这个是提示cookie没有填写正确吗？

**Comment by TNanko** [comment]
> 使用的是docker部署的，进去之后，手动运行命令：
> root@tnanko_scripts:/Scripts/scripts $ python bilibili.py
> 获取最新配置文件版本成功！
> 当前配置文件为最新版本
> 检测到最新的脚本版本号为v1.1.1，当前脚本版本号：v1.0.0
> 未执行该任务，如需执行请在配置文件的对应的任务中，将参数 enable 设置为 true
> 
> 检查了config.yaml，确实修改为true：
> bilibili:
> # 使用前请阅读 https://github.com/TNanko/leam/blob/leam/docs/bilibili.md
> enable: true # true 启用脚本； false 不启用脚本（默认不启用脚本）
> version: v1.1.1
> skip_check_script_version: false # 默认不跳过版本检测
> notify: true # true 启用消息推送； false 不启用消息推送（默认发消息推送）
> notify_mode: # 如果全都配置了，可以根据自身需求进行消息推送方式的选择，不需要的可以注释掉或者删除。推荐 bark
> # - bark
> # - telegram_bot
> # - dingding_bot
> - server_chan
> scripts_filename: 'bilibili.py'
> 然后手动把github里面的biblibili.py的内容复制替换了docker里面的文件
> 再次运行，还是报同样的错误
> 求解

你好,由于个人能力有限,我不会docker,而且脚本基本上不会向下兼容(这是个吐槽点)
建议使用源码直接部署,当然,docker版也即将会更新

**Comment by TNanko** [comment]
> 然后，我直接wget了这个bilibili.py，再次运行，这次显示如下：
> 获取最新配置文件版本成功！
> 当前配置文件为最新版本
> 检测到最新的脚本版本号为v1.1.1，当前脚本版本号：v1.0.0
> Traceback (most recent call last):
> File "/Scripts/scripts/bilibili.py", line 153, in
> main()
> File "/Scripts/scripts/bilibili.py", line 149, in main
> bilibili()
> File "/Scripts/scripts/bilibili.py", line 111, in bilibili
> content += f"【bilibili】签到失败！说明：{sign_result['message']}"
> TypeError: 'NoneType' object is not subscriptable
> 
> 这个是提示cookie没有填写正确吗？

可能是,你可以参考的[教程](https://github.com/TNanko/leam/blob/master/docs/bilibili.md) 重新部署一下
