### ISSUE TITLE
qq_read报错

### ISSUE THREAD

**Issue by wolfsiberia** [TNanko/leam#42]
程序报错，请带上错误日志
Traceback (most recent call last):
  File "/Scripts/scripts/qq_read.py", line 523, in qq_read
    if not today_read_time['readTimeRewardTask'][len(today_read_time['readTimeRewardTask']) - 1]['doneFlag']:
TypeError: object of type 'NoneType' has no len()

**Comment by TNanko** [comment]
> 程序报错，请带上错误日志
> Traceback (most recent call last):
> File "/Scripts/scripts/qq_read.py", line 523, in qq_read
> if not today_read_time['readTimeRewardTask'][len(today_read_time['readTimeRewardTask']) - 1]['doneFlag']:
> TypeError: object of type 'NoneType' has no len()

抱歉,由于前段时间的脚本封禁,所以这个脚本不再维护,所以可能这段时间内企鹅读书接口变了.很抱歉,你可以抓包试一下

**Comment by zqh2333** [comment]
同这个问题 请问解决没有
